### ISSUE TITLE
add-multimedia-repo

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-welcome#3]
The bl-welcome script is failing when trying to install from
`http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2014.2_all.deb`

...but the current package is

`http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2015.6_all.deb`

**Comment by johnraff** [comment]
Indeed. Thanks.
Now fixed and pushed.
