### ISSUE TITLE
Declining apt-update and apt-upgrade quits bl-welcome script

### ISSUE THREAD

**Issue by smacz42** [BunsenLabs/bunsen-welcome#5]
In the bl-welcome script, if `apt-update` or `apt-upgrade` are declined, (Update Software Sources/Upgrade Installed Packages) then the script quits altogether. 

In the same vein that the script does not prompt to initiate a internet connection test, I propose that the script may want to automatically run `apt-get update` and `apt-get upgrade` if indeed they are necessary.

If the maintainers feel that at times it is _not_ necessary to run those commands, then might I suggest that declining these actions not prematurely exit the script?

For myself, there is no reason for me to decline the commands, and would be all for having them run automatically and not even having an option to decline them as (IMHO) they are fundamentally neccessary for performing the actions which follow. Is there a scenario which I am overlooking in which the user would, for good reasons, _not_ update/upgrade their system but attempt to install additional software onto that system?

**Comment by johnraff** [comment]
@smacz42 thank you for the report.

> Is there a scenario which I am overlooking in which the user would, for good reasons, not update/upgrade their system but attempt to install additional software onto that system?

Well, no, hence the exit if the update/upgrade is declined. The opportunity to decline is because, unlike a network test, this is an operation on the user's system. It might just be that the user remembers an issue that needs resolving before running those commands - maybe an edit to sources.list...

In fact, _all_ the actions which require root powers in the script are taken only after a second confirmation from the user. I don't think that is a bad principle to follow.

**Comment by smacz42** [comment]
Yes, not passing the `-y` switch does require a second confirmation via `apt-get`, and is an excellent principle to follow. I get now why you would want it to take the actions that it does.

Before I close this issue out, it follows then that the initial "Ugrade Software Sources" states that
> Before we can continue...
However, the "Upgrade Installed Packages" screen asks
> Would you like to...
And quits if declined. 

Now, at this point I'm just arguing semantics, but might the more assertive "Before we can continue..." phasing be just as appropriate to include on the latter screen as well? It seems to me that it would reflect the weight of the decision more accurately than "Would you like to..." does.

(Just my $.02)

**Comment by smacz42** [comment]
Yes, not passing the `-y` switch would result in `apt-get` requiring a second confirmation. I think it is an excellent principle to follow. Now I get why you would want it to have that behavior. Thank you once again for taking the time to offer me an explanation.
