### ISSUE TITLE
Run bunsen-welcome non-interactively

### ISSUE THREAD

**Issue by nalipaz** [BunsenLabs/bunsen-welcome#6]
I would like to be able to run the bl-welcome without my interaction, perhaps by creating a configuration file to specify the options or something. I am fine with the sudo prompt, but all the other prompts asking for input I would like to avoid. Any chance this could be done?

**Comment by johnraff** [comment]
I'm not quite sure what type of user you have in mind here, to be honest. Are you saying that editing a config file would be easier to do than responding to prompts in an interactive script? Or are you planning to write one config file and automate the welcome script process for a number of machines?

Either way, it would likely involve a major rewrite of the script.

**Comment by nalipaz** [comment]
I planned on using it to automate installs on multiple machines. However, I can imagine if the usage of the feature were too low that a rewrite would not be very worth it. I guess alternatively I can look into each of the commands it does, run my own script, and abort the bl-welcome script.

**Comment by johnraff** [comment]
That sounds like the way to go, to be honest. You could probably pull some usable code out of the script, and the files it sources, but as it is it's very much oriented to an interactive style.

**Comment by nalipaz** [comment]
Okay, well I suggest closing this as 'won't fix' if you have a label for that. Thanks for entertaining the idea.

**Comment by johnraff** [comment]
It is an interesting idea actually...

Anyway, OK I'll close it, and attach a wontfix label. 
Thanks for the suggestion - input like this is always appreciated.
