### ISSUE TITLE
lithium: Include most recent commit in new release

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-welcome#9]
Commit 89353e484d38557f997d305db400959b9b4af2ab already pushed to lithium.

Fixes missing icedtea8 dependency.

Already fixed in helium.

**Comment by johnraff** [comment]
Thanks!
There are no longer any icedtea browser plugins, due to recent Firefox changes.

Incidentally, the more recent java 11 packages are available in Debian Buster, so I was planning to propose replacing openjdk-8-jre with openjdk-11-jre.

**Comment by johnraff** [comment]
openjdk-8-jre now replaced with default-jre in lithium. 747d9f1
